// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EXnzo_1F4xDiTpM_Qu3UlqWuRr7XTug',
    appId: '1:847268283050:web:0fe5c81427adcde9d886d3',
    messagingSenderId: '847268283050',
    projectId: 'auth-e43c7',
    authDomain: 'auth-e43c7.firebaseapp.com',
    storageBucket: 'auth-e43c7.appspot.com',
    measurementId: 'G-YE8C7QHWG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0kipiPK6TbMlzx2lFkwVPK-qEZODitI',
    appId: '1:847268283050:android:034a5310cbf43084d886d3',
    messagingSenderId: '847268283050',
    projectId: 'auth-e43c7',
    storageBucket: 'auth-e43c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtlI-jMKTcEdqLu0qkU05mnHfm95AEvg',
    appId: '1:847268283050:ios:3e829ee796f17aa5d886d3',
    messagingSenderId: '847268283050',
    projectId: 'auth-e43c7',
    storageBucket: 'auth-e43c7.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtlI-jMKTcEdqLu0qkU05mnHfm95AEvg',
    appId: '1:847268283050:ios:9b151ac9c441340ad886d3',
    messagingSenderId: '847268283050',
    projectId: 'auth-e43c7',
    storageBucket: 'auth-e43c7.appspot.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
